// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIXPLqnPEDkt5BOQO-jYQQUA0DfUaMm5Q',
    appId: '1:579260522939:web:669b13110a253c5c05e49e',
    messagingSenderId: '579260522939',
    projectId: 'uas-mp-oktafiana',
    authDomain: 'uas-mp-oktafiana.firebaseapp.com',
    storageBucket: 'uas-mp-oktafiana.firebasestorage.app',
    measurementId: 'G-0C6K71P8RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15Zy9A3vaYw2EvqpdSol0z10J9dl3Vuw',
    appId: '1:579260522939:android:70fae802a702101605e49e',
    messagingSenderId: '579260522939',
    projectId: 'uas-mp-oktafiana',
    storageBucket: 'uas-mp-oktafiana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTfRYHgmhbI-IUvtf-6owf7MF9eJkVXI',
    appId: '1:579260522939:ios:d559199fc9ead51905e49e',
    messagingSenderId: '579260522939',
    projectId: 'uas-mp-oktafiana',
    storageBucket: 'uas-mp-oktafiana.firebasestorage.app',
    iosClientId: '579260522939-anog8i5i0g7feukslj1sqd7pjpj5u9fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTfRYHgmhbI-IUvtf-6owf7MF9eJkVXI',
    appId: '1:579260522939:ios:d559199fc9ead51905e49e',
    messagingSenderId: '579260522939',
    projectId: 'uas-mp-oktafiana',
    storageBucket: 'uas-mp-oktafiana.firebasestorage.app',
    iosClientId: '579260522939-anog8i5i0g7feukslj1sqd7pjpj5u9fq.apps.googleusercontent.com',
    iosBundleId: 'com.example.laundryBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIXPLqnPEDkt5BOQO-jYQQUA0DfUaMm5Q',
    appId: '1:579260522939:web:eb5a5c7be79a1d9c05e49e',
    messagingSenderId: '579260522939',
    projectId: 'uas-mp-oktafiana',
    authDomain: 'uas-mp-oktafiana.firebaseapp.com',
    storageBucket: 'uas-mp-oktafiana.firebasestorage.app',
    measurementId: 'G-0S90R350VT',
  );
}
